version: '2'
services:
    hello-docker:
        container_name: hello-docker
        build:
            context: hello-docker
            dockerfile: Dockerfile
        image: hello-docker
        ports:
            - "8080:8080"
        environment:
            DB_UPSTREAM: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:3000
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge